import json
from pathlib import Path
from typing import Dict, Iterable, List

from .models import FileInfo, RepoBrief


def render_markdown(brief: RepoBrief, *, profile: str = "generic") -> str:
    lines: List[str] = []
    lines.append(f"# Repo Brief: {brief.name}")
    lines.append("")
    lines.append(_profile_intro(profile))
    lines.append("")
    lines.append("## Snapshot")
    lines.extend(
        [
            f"- Root: `{brief.root}`",
            f"- Files scanned: {brief.file_count}",
            f"- Lines scanned: {brief.line_count}",
            f"- Bytes scanned: {_format_bytes(brief.total_bytes)}",
            f"- Stack signals: {', '.join(brief.stack)}",
        ]
    )
    if brief.language_bytes:
        lines.append(f"- Languages: {_language_summary(brief.language_bytes)}")
    lines.append("")

    _append_section(lines, "Likely Commands", _command_lines(brief.commands))
    _append_file_section(lines, "Entrypoints", brief.entrypoints)
    _append_file_section(lines, "Manifests", brief.manifests)
    _append_file_section(lines, "Tests", brief.tests)
    _append_file_section(lines, "CI And Config", brief.ci + brief.configs)
    _append_file_section(lines, "Docs", brief.docs)

    lines.append("## Project Map")
    if brief.tree_lines:
        lines.append("```text")
        lines.extend(brief.tree_lines)
        lines.append("```")
    else:
        lines.append("_No files matched the scan filters._")
    lines.append("")

    if brief.warnings:
        lines.append("## Attention Points")
        lines.extend(f"- {warning}" for warning in brief.warnings)
        lines.append("")

    lines.append("## First Files To Read")
    for item in brief.top_files[:12]:
        lines.append(f"- `{item.path}` - {item.reason}, {item.lines} lines, {_format_bytes(item.size)}")
    lines.append("")

    if brief.snippets:
        lines.append("## Compact Snippets")
        for snippet in brief.snippets:
            lines.append(f"### `{snippet.path}`")
            lines.append(f"Reason: {snippet.reason}.")
            lines.append("")
            lines.append("```text")
            lines.append(snippet.content.rstrip())
            lines.append("```")
            lines.append("")

    lines.append("## Prompt Pack")
    lines.append("Paste this at the start of a coding-agent session:")
    lines.append("")
    lines.append("```text")
    lines.append(f"You are working in `{brief.name}`.")
    lines.append("Use the repo brief above as the starting map.")
    lines.append("Before editing, inspect the listed entrypoints, manifests, tests, and agent instructions.")
    lines.append("Keep changes scoped, follow existing project style, and run the likely commands when relevant.")
    lines.append("If a convention is unclear, infer it from nearby files before introducing a new pattern.")
    lines.append("```")
    lines.append("")
    lines.append("_Generated by RepoWhisper._")
    return "\n".join(lines).rstrip() + "\n"


def render_agents(brief: RepoBrief) -> str:
    lines: List[str] = [
        "# AGENTS.md",
        "",
        "This file was generated by RepoWhisper. Edit it with any repo-specific rules that humans know but tools cannot infer.",
        "",
        "## Project Shape",
        f"- Stack signals: {', '.join(brief.stack)}",
        f"- Primary entrypoints: {_inline_paths(brief.entrypoints) or 'none detected'}",
        f"- Test surface: {_inline_paths(brief.tests[:8]) or 'none detected'}",
        "",
        "## Commands",
    ]
    command_lines = _command_lines(brief.commands)
    lines.extend(command_lines if command_lines else ["- No commands detected."])
    lines.extend(
        [
            "",
            "## Working Rules",
            "- Read nearby files before introducing new abstractions.",
            "- Keep generated, dependency, cache, and build folders out of manual edits.",
            "- Prefer small, reviewable changes and update tests when behavior changes.",
            "- If a command fails because dependencies are missing, report the exact command and failure.",
            "",
            "## Useful First Reads",
        ]
    )
    first_reads = [item for item in brief.top_files if item.path != "AGENTS.md"]
    for item in first_reads[:12]:
        lines.append(f"- `{item.path}` - {item.reason}")
    lines.append("")
    return "\n".join(lines)


def render_json(brief: RepoBrief) -> str:
    payload = {
        "name": brief.name,
        "root": str(brief.root),
        "file_count": brief.file_count,
        "line_count": brief.line_count,
        "total_bytes": brief.total_bytes,
        "skipped_count": brief.skipped_count,
        "language_bytes": brief.language_bytes,
        "stack": brief.stack,
        "commands": brief.commands,
        "warnings": brief.warnings,
        "entrypoints": [_file_dict(item) for item in brief.entrypoints],
        "manifests": [_file_dict(item) for item in brief.manifests],
        "tests": [_file_dict(item) for item in brief.tests],
        "docs": [_file_dict(item) for item in brief.docs],
        "configs": [_file_dict(item) for item in brief.configs],
        "ci": [_file_dict(item) for item in brief.ci],
        "top_files": [_file_dict(item) for item in brief.top_files[:20]],
        "tree": brief.tree_lines,
        "snippets": [
            {
                "path": snippet.path,
                "start_line": snippet.start_line,
                "reason": snippet.reason,
                "content": snippet.content,
            }
            for snippet in brief.snippets
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _profile_intro(profile: str) -> str:
    profile = profile.lower()
    if profile == "codex":
        return "A compact context pack for Codex-style autonomous code work."
    if profile == "claude":
        return "A compact context pack for long-form code reasoning and implementation."
    if profile == "cursor":
        return "A compact context pack for editor-native AI coding sessions."
    return "A compact context pack for AI-assisted code work."


def _append_section(lines: List[str], title: str, items: Iterable[str]) -> None:
    values = list(items)
    if not values:
        return
    lines.append(f"## {title}")
    lines.extend(values)
    lines.append("")


def _append_file_section(lines: List[str], title: str, files: Iterable[FileInfo]) -> None:
    items = list(files)
    if not items:
        return
    lines.append(f"## {title}")
    for item in items[:16]:
        lines.append(f"- `{item.path}` - {item.reason}, {item.lines} lines")
    if len(items) > 16:
        lines.append(f"- ... {len(items) - 16} more")
    lines.append("")


def _command_lines(commands: Dict[str, List[str]]) -> List[str]:
    lines: List[str] = []
    for group, values in commands.items():
        for command in values:
            lines.append(f"- `{command}` ({group})")
    return lines


def _language_summary(language_bytes: Dict[str, int]) -> str:
    total = sum(language_bytes.values()) or 1
    parts: List[str] = []
    for language, size in list(language_bytes.items())[:6]:
        pct = round((size / total) * 100)
        parts.append(f"{language} {pct}%")
    return ", ".join(parts)


def _format_bytes(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    if size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    return f"{size / (1024 * 1024):.1f} MB"


def _inline_paths(files: Iterable[FileInfo]) -> str:
    return ", ".join(f"`{item.path}`" for item in files)


def _file_dict(item: FileInfo) -> Dict[str, object]:
    return {
        "path": item.path,
        "suffix": item.suffix,
        "size": item.size,
        "lines": item.lines,
        "kind": item.kind,
        "score": item.score,
        "reason": item.reason,
    }
